
---

# Block-dyad sampling

Consider a community like network:

.pull-left[
```{r settings, results='hide'}
n <- 200
alpha <-  c(1/3,1/3,1/3)
pi    <- .15 + diag(3) * .25
theta <- list(mean = pi)
pi
```
]

.pull-right[
```{r settings show, echo = FALSE}
n <- 200
alpha <-  c(1/3,1/3,1/3)
pi    <- .15 + diag(3) * .25
theta <- list(mean = pi)
pi
```
]

Define sampling matrices with decreasing agreement with $\pi$

```{r, results='hide', echo = FALSE, fig.dim=c(10, 4)}
delta <- seq(0, .35, 0.05)
list_psi <- map(delta, ~matrix(0.1 + .x, 3, 3) + diag(3) * (max(delta) - .x))
par(mfrow = c(2, 4))
lapply(list_psi, image, xaxt= "n", yaxt= "n", breaks = seq(0, 0.5, len = length(delta)+1), col = rev(gray.colors(length(delta))))
```

---

# Performance of MAR vs MNAR

```{r simuMNAR, cache = TRUE, message = FALSE, warning=FALSE, results='hide', echo = FALSE}
control <- list(threshold = 1e-2, maxIter = 50, fixPointIter = 3, trace = 0)
nbrSimu <- 100
library(sbm)
library(missSBM)
library(future.apply)
library(tidyverse)
library(viridis)
RES <- lapply(1:nbrSimu, function(i) {
  res <- future.apply::future_lapply(list_psi, function(psi) {

  A <- sbm::sampleSimpleSBM(nbNodes = n, blockProp = alpha, connectParam = theta, model = "bernoulli" )

  A_obs <-
    missSBM::observeNetwork(A$networkData, sampling="block-dyad", clusters = A$memberships, parameters = psi) %>%
    missSBM:::partlyObservedNetwork$new()

  cl_init <- A_obs$clustering(1:3)[[3]]

  MAR <- missSBM_fit$new(A_obs, "dyad", cl_init)
  out <- MAR$doVEM(control)

  MNAR <- missSBM_fit$new(A_obs, "block-dyad", cl_init)
  out <- MNAR$doVEM(control)

  res <- data.frame(
    ARI = c(aricode::ARI(cl_init,A$memberships), aricode::ARI(MNAR$fittedSBM$memberships,A$memberships), aricode::ARI(MAR$fittedSBM$memberships,A$memberships)),
    MSE = c(NA, sqrt(sum((MNAR$fittedSBM$connectParam$mean-theta$mean)^2)), sqrt(sum((MAR$fittedSBM$connectParam$mean-theta$mean)^2))),
    Psi = c(NA, sqrt(sum((MNAR$fittedSampling$parameters-psi)^2)), NA),
    variant = c("init", "MNAR", "MAR")
  )
  res$simu  <- i
  res$delta <- psi[2,1] - psi[1,1]
  res
  }) %>% purrr::reduce(rbind)
  res
}) %>% reduce(rbind)

```

```{r, echo = FALSE, fig.dim=c(15, 7), fig.align='center'}
p <- RES %>% dplyr::select(-Psi) %>% pivot_longer(c(ARI, MSE), names_to = "measure") %>%
  filter(variant != "init") %>%
  group_by(variant) %>%
  ggplot() + theme_bw() + viridis::scale_colour_viridis(discrete = TRUE) + viridis::scale_fill_viridis(discrete = TRUE) +
  aes(x = factor(delta), y = value, fill = variant) +
  geom_boxplot() + geom_point() + facet_wrap(~ measure, scales = "free")

print(p)
```

100 replicates. The closer $\delta$ to zero, the closer to the MAR case.
